#!/usr/bin/env bash
# bash file for the work


if [ $# == 2 ]; then
    domain=$1
    subdomain=$2
    SUB_DOMAINS=$subdomain
else
    domain=$1
    SUB_DOMAINS=("www" "lb-01" "web-01" "web-02")
fi

for sub in ${SUB_DOMAINS[@]}; do
    record_type=$(dig +short -t CNAME "$sub.$domain" || dig +short -t A "$sub.$domain" | awk '{print $1}')
    destination=$(dig +short "$sub.$domain" | awk '{print $1}')
    echo "The subdomain $sub is a $record_type record and points to $destination"
done
